import type { Metadata } from "next";
import "../globals.css";
import { MotionProvider } from "@/components/providers";

export const metadata: Metadata = {
  title: "Group App",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <>
      <MotionProvider>{children}</MotionProvider>
    </>
  );
}
