import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Group App",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <>
      <main className="px-4 py-6">{children}</main>
    </>
  );
}
