// app/app/layout.tsx
import type { Metadata } from 'next'
import { AppLayoutClient } from './AppLayoutClient'

export const metadata: Metadata = {
  title: 'App | Group App',
  description: 'Generated by create next app',
}

export default function AppLayout({ children }: { children: React.ReactNode }) {
  return <AppLayoutClient>{children}</AppLayoutClient>
}
