import type { Metadata } from "next";
import "@/styles/global.css";
import { MotionProvider } from "@/components/providers"

export const metadata: Metadata = {
  title: "Group App",
  description: "Generated by create next app",
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <>
      <MotionProvider>
        <div className="px-4">
          {children}
        </div>
      </MotionProvider>
    </>
  );
}
