// app/app/layout.tsx
import type { Metadata } from "next"
import { AuthGuard } from "./AuthGuard"
import { AppBadgeProvider } from "@/context/AppBadgeContext"

export const metadata: Metadata = {
  title: "App | Group App",
  description: "Generated by create next app",
}

export default function AppLayout({ children }: { children: React.ReactNode }) {
  return (
    <AuthGuard>
      <AppBadgeProvider>
        {children}
      </AppBadgeProvider>
    </AuthGuard>
  )
}