import type { Metadata } from "next"
import "@/styles/global.css"
import { MotionProvider } from "@/components/providers"
import { GroupSeenClient } from "./components/group-seen-client"

export const metadata: Metadata = {
  title: "Group App",
  description: "Generated by create next app",
}

export default function GroupLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { groupId: string }
}) {
  return (
    <MotionProvider>
      <div className="max-w-4xl mx-auto">
        <GroupSeenClient groupId={params.groupId} />
        {children}
      </div>
    </MotionProvider>
  )
}