import type { Metadata } from "next"
import "@/styles/global.css"
import { MotionProvider } from "@/components/providers"
import { GroupSeenClient } from "./components/group-seen-client"

export const metadata: Metadata = {
  title: "Group App",
  description: "Generated by create next app",
}

// ✅ params sekarang Promise
export default async function GroupLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: Promise<{ groupId: string }>
}) {
  const { groupId } = await params   // ✅ tunggu promise

  return (
    <MotionProvider>
      <div className="max-w-4xl mx-auto">
        <GroupSeenClient groupId={groupId} />
        {children}
      </div>
    </MotionProvider>
  )
}